import { useState, useEffect } from 'react';
import { Plus, Server, AlertTriangle, Info, Download, Copy, Check, Radio } from 'lucide-react';
import type { AllConfigs } from '../../../types';
import { LoggerSection } from './SharedComponents';

interface Props {
  configs: AllConfigs;
  onChange: (c: AllConfigs) => void;
  onApply?: (configs: AllConfigs) => Promise<void>;
  editSgwuData?: { pfcpAddress: string; gtpuAddress: string; tac: string; label: string };
  onEditSgwuDataConsumed?: () => void;
}

interface RemoteSgwuForm {
  label:       string;
  pfcpAddress: string;
  gtpuAddress: string;
  tac:         string;
  apn:         string;
  eCellId:     string;
  logPath:     string;
}

function isLoopback(ip: string): boolean {
  return ip.startsWith('127.') || ip === 'localhost';
}

// ── YAML Generator ────────────────────────────────────────────────────────────

function generateRemoteSgwuYaml(form: RemoteSgwuForm, sgwcDisplayAddress: string): string {
  const lines: string[] = [];

  lines.push(`logger:`);
  lines.push(`  file:`);
  lines.push(`    path: ${form.logPath || '/var/log/open5gs/sgwu.log'}`);
  lines.push(``);
  lines.push(`# Remote SGW-U: ${form.label || 'Edge Site'}`);
  lines.push(`# Generated by open5gs-nms`);
  lines.push(`# Deploy this file to: /etc/open5gs/sgwu.yaml on the remote SGW-U host`);
  lines.push(`# The SGW-C at ${sgwcDisplayAddress} must be able to reach ${form.pfcpAddress || '<PFCP-IP>'} on UDP/8805`);
  lines.push(``);
  lines.push(`sgwu:`);
  lines.push(`  pfcp:`);
  lines.push(`    server:`);
  lines.push(`      - address: ${form.pfcpAddress || '10.0.1.158'}`);
  if (sgwcDisplayAddress && sgwcDisplayAddress !== '<SGW-C-routable-IP>') {
    lines.push(`    client:`);
    lines.push(`      sgwc:`);
    lines.push(`        - address: ${sgwcDisplayAddress}`);
  }
  lines.push(``);
  lines.push(`  gtpu:`);
  lines.push(`    server:`);
  lines.push(`      - address: ${form.gtpuAddress || form.pfcpAddress || '10.0.1.158'}`);
  lines.push(``);

  return lines.join('\n');
}

// ── Main component ────────────────────────────────────────────────────────────

export function SgwuEditor({ configs, onChange, onApply, editSgwuData, onEditSgwuDataConsumed }: Props): JSX.Element {
  // ── Local SGW-U (sgwu.yaml) ──
  const sgwuFullYaml = configs.sgwu as any;
  const sgwu = sgwuFullYaml?.sgwu || {};
  const pfcpServer = sgwu.pfcp?.server?.[0] || { address: '127.0.0.6' };
  const gtpuServer = sgwu.gtpu?.server?.[0] || { address: '10.0.1.175' };

  // ── SGW-C (sgwc.yaml) — PFCP SGW-U client list ──
  const sgwcFullYaml = configs.sgwc as any;
  const sgwc = sgwcFullYaml?.sgwc || {};
  const sgwuClients: Array<{ address: string }> = sgwc.pfcp?.client?.sgwu || [{ address: '127.0.0.6' }];

  const sgwcPfcpServer0: string = sgwc.pfcp?.server?.[0]?.address || '';
  const sgwcPfcpServer1: string = sgwc.pfcp?.server?.[1]?.address || '';

  const sgwcRealAddress: string =
    (!isLoopback(sgwcPfcpServer1) && sgwcPfcpServer1 ? sgwcPfcpServer1 : '') ||
    (!isLoopback(sgwcPfcpServer0) && sgwcPfcpServer0 ? sgwcPfcpServer0 : '') ||
    '';
  const sgwcDisplayAddress = sgwcRealAddress || '<SGW-C-routable-IP>';

  // ── Remote SGW-U generator state ──
  const [remoteForm, setRemoteForm] = useState<RemoteSgwuForm>({
    label:       '',
    pfcpAddress: '',
    gtpuAddress: '',
    tac:         '',
    apn:         '',
    eCellId:     '',
    logPath:     '/var/log/open5gs/sgwu.log',
  });
  const [copied,   setCopied]   = useState(false);
  const [applying, setApplying] = useState(false);
  const [applied,  setApplied]  = useState(false);

  // Pre-populate form when navigated here from SgwcEditor
  useEffect(() => {
    if (!editSgwuData) return;
    setRemoteForm(prev => ({
      ...prev,
      pfcpAddress: editSgwuData.pfcpAddress || prev.pfcpAddress,
      gtpuAddress: editSgwuData.gtpuAddress || prev.gtpuAddress,
      tac:         editSgwuData.tac         || prev.tac,
      label:       editSgwuData.label       || prev.label,
    }));
    onEditSgwuDataConsumed?.();
    setTimeout(() => {
      document.getElementById('remote-sgwu-generator')?.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }, 100);
  }, [editSgwuData]);

  const setRemote = (patch: Partial<RemoteSgwuForm>) =>
    setRemoteForm(prev => ({ ...prev, ...patch }));

  const generatedYaml = generateRemoteSgwuYaml(remoteForm, sgwcDisplayAddress);

  const handleCopy = () => {
    navigator.clipboard.writeText(generatedYaml).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const handleDownload = () => {
    const blob = new Blob([generatedYaml], { type: 'text/yaml' });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    const name = remoteForm.label
      ? remoteForm.label.toLowerCase().replace(/[^a-z0-9]/g, '-')
      : 'remote-sgwu';
    a.href     = url;
    a.download = `sgwu-${name}.yaml`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const remoteAlreadyInSgwc = remoteForm.pfcpAddress
    ? sgwuClients.some(c => c.address === remoteForm.pfcpAddress)
    : false;

  const handleAddToSgwc = async () => {
    if (!remoteForm.pfcpAddress) return;

    const newClient: any = { address: remoteForm.pfcpAddress };
    if (remoteForm.tac) {
      const tacs = remoteForm.tac.split(',').map(t => parseInt(t.trim())).filter(n => !isNaN(n));
      if (tacs.length === 1) newClient.tac = tacs[0];
      else if (tacs.length > 1) newClient.tac = tacs;
    } else if (remoteForm.apn) {
      const apns = remoteForm.apn.split(',').map(a => a.trim()).filter(Boolean);
      newClient.apn = apns.length === 1 ? apns[0] : apns;
    } else if (remoteForm.eCellId) {
      const ids = remoteForm.eCellId.split(',').map(s => s.trim()).filter(Boolean);
      newClient.e_cell_id = ids.length === 1 ? ids[0] : ids;
    }

    const alreadyIn = sgwuClients.some(c => c.address === remoteForm.pfcpAddress);
    const newClients = alreadyIn
      ? sgwuClients.map(c => c.address === remoteForm.pfcpAddress ? newClient : c)
      : [...sgwuClients, newClient];

    const updatedConfigs: AllConfigs = {
      ...configs,
      sgwc: {
        ...sgwcFullYaml,
        sgwc: {
          ...sgwc,
          pfcp: {
            ...sgwc.pfcp,
            client: { ...sgwc.pfcp?.client, sgwu: newClients },
          },
        },
      },
    };

    onChange(updatedConfigs);
    if (onApply) await onApply(updatedConfigs);
  };

  const handleAddToSgwcAndApply = async () => {
    setApplying(true);
    try {
      await handleAddToSgwc();
      setApplied(true);
      setTimeout(() => setApplied(false), 3000);
    } finally {
      setApplying(false);
    }
  };

  // ── Updaters ──────────────────────────────────────────────────────────────

  const updateSgwu = (partial: any) => {
    onChange({ ...configs, sgwu: { ...sgwuFullYaml, sgwu: { ...sgwu, ...partial } } });
  };

  const updateLogger = (logger: any) => {
    onChange({ ...configs, sgwu: { ...sgwuFullYaml, logger } });
  };

  if (!sgwu?.pfcp?.server || sgwu.pfcp.server.length === 0) {
    return <div className="text-nms-text-dim py-4">Loading SGW-U configuration...</div>;
  }

  return (
    <div className="space-y-8">

      {/* ── Section 1: Local SGW-U ── */}
      <div>
        <div className="flex items-center gap-3 mb-4">
          <div className="p-2 rounded-lg bg-nms-accent/10 text-nms-accent">
            <Server className="w-4 h-4" />
          </div>
          <div>
            <h3 className="text-base font-semibold font-display text-nms-text">
              Local SGW-U — <span className="font-mono text-nms-accent">/etc/open5gs/sgwu.yaml</span>
            </h3>
            <p className="text-xs text-nms-text-dim">
              The SGW-U running on this Open5GS host. PFCP can use loopback; GTP-U (S1-U) must use
              a real routable IP that eNodeBs can reach.
            </p>
          </div>
        </div>

        <div className="nms-card space-y-6">
          {/* PFCP Server */}
          <div>
            <h4 className="text-sm font-semibold font-display text-nms-accent mb-3">
              PFCP Server (Gxc — SGW-C control plane)
            </h4>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="nms-label">Address</label>
                <input
                  className="nms-input font-mono text-sm"
                  value={pfcpServer.address}
                  onChange={e => updateSgwu({ pfcp: { ...sgwu.pfcp, server: [{ ...pfcpServer, address: e.target.value }] } })}
                  placeholder="127.0.0.6"
                />
              </div>
              <div>
                <label className="nms-label">Port</label>
                <input
                  type="number"
                  className="nms-input font-mono text-sm"
                  value={pfcpServer.port ?? ''}
                  onChange={e => {
                    const updated = { ...pfcpServer };
                    if (e.target.value) (updated as any).port = parseInt(e.target.value) || 8805;
                    else delete (updated as any).port;
                    updateSgwu({ pfcp: { ...sgwu.pfcp, server: [updated] } });
                  }}
                  placeholder="8805 (default)"
                />
              </div>
            </div>
          </div>

          {/* PFCP Client (SGW-C address) */}
          <div>
            <h4 className="text-sm font-semibold font-display text-nms-accent mb-1">
              PFCP Client — SGW-C address
              <span className="text-nms-text-dim font-normal ml-2 text-xs">(optional)</span>
            </h4>
            <p className="text-xs text-nms-text-dim mb-3">
              When set, the SGW-U actively dials the SGW-C on startup and re-associates if the SGW-C restarts.
              Required for remote SGW-U deployments. Leave blank if SGW-C and SGW-U are on the same host
              and SGW-C is configured to dial SGW-U.
            </p>
            <input
              className="nms-input font-mono text-sm"
              value={(sgwu.pfcp?.client?.sgwc?.[0]?.address) || ''}
              onChange={e => {
                const v = e.target.value.trim();
                const pfcp = { ...sgwu.pfcp };
                if (v) {
                  pfcp.client = { sgwc: [{ address: v }] };
                } else {
                  delete pfcp.client;
                }
                updateSgwu({ pfcp });
              }}
              placeholder="127.0.0.3  or  10.0.1.177 for remote"
            />
          </div>

          {/* GTP-U Server */}
          <div>
            <h4 className="text-sm font-semibold font-display text-nms-accent mb-1">
              GTP-U Server (S1-U — eNodeB user plane)
            </h4>
            <p className="text-xs text-nms-text-dim mb-3">
              Must be a real routable IP — eNodeBs send UE user traffic directly here over UDP/2152. Cannot be loopback.
            </p>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="nms-label">Address</label>
                <input
                  className="nms-input font-mono text-sm"
                  value={gtpuServer.address}
                  onChange={e => updateSgwu({ gtpu: { server: [{ ...gtpuServer, address: e.target.value }] } })}
                  placeholder="10.0.1.175"
                />
                {isLoopback(gtpuServer.address) && (
                  <div className="mt-1.5 flex items-start gap-1.5 text-xs text-amber-400">
                    <AlertTriangle className="w-3.5 h-3.5 shrink-0 mt-0.5" />
                    <span>GTP-U address is loopback — remote eNodeBs cannot send user traffic here.</span>
                  </div>
                )}
              </div>
              <div>
                <label className="nms-label">Port</label>
                <input
                  type="number"
                  className="nms-input font-mono text-sm"
                  value={gtpuServer.port ?? ''}
                  onChange={e => {
                    const updated = { ...gtpuServer };
                    if (e.target.value) (updated as any).port = parseInt(e.target.value) || 2152;
                    else delete (updated as any).port;
                    updateSgwu({ gtpu: { server: [updated] } });
                  }}
                  placeholder="2152 (default)"
                />
              </div>
            </div>
          </div>

          <LoggerSection logger={sgwuFullYaml.logger || {}} onChange={updateLogger} />
        </div>
      </div>

      {/* ── Section 2: Remote SGW-U YAML Generator ── */}
      <div id="remote-sgwu-generator">
        <div className="flex items-center gap-3 mb-4">
          <div className="p-2 rounded-lg bg-purple-500/10 text-purple-400">
            <Radio className="w-4 h-4" />
          </div>
          <div>
            <h3 className="text-base font-semibold font-display text-nms-text">
              Remote SGW-U Config Generator
            </h3>
            <p className="text-xs text-nms-text-dim">
              Fill in the details for your remote edge SGW-U. This generates a ready-to-deploy{' '}
              <span className="font-mono">sgwu.yaml</span> to copy to the remote machine.
              The remote SGW-U only needs <span className="font-mono">open5gs-sgwu</span> installed.
            </p>
          </div>
        </div>

        {/* How it works explainer */}
        <div className="nms-card bg-purple-500/5 border-purple-500/20 mb-4">
          <div className="flex items-start gap-3">
            <Info className="w-4 h-4 text-purple-400 mt-0.5 shrink-0" />
            <div className="text-xs text-nms-text-dim space-y-1">
              <p className="font-semibold text-nms-text">How distributed SGW-U works:</p>
              <p>
                <span className="text-purple-300">SGW-C → Remote SGW-U</span> over{' '}
                <span className="font-mono">PFCP/Gxc (UDP/8805)</span> — the SGW-C sends session
                rules to the remote SGW-U. The central SGW-C is at{' '}
                <span className="font-mono text-nms-accent">{sgwcDisplayAddress}</span>.
              </p>
              <p>
                <span className="text-purple-300">eNodeB → Remote SGW-U</span> over{' '}
                <span className="font-mono">GTP-U/S1-U (UDP/2152)</span> — UE user traffic goes
                directly from the eNodeB to the remote SGW-U, never touching the central site WAN.
              </p>
              <p>Both the PFCP and GTP-U addresses must be routable between sites. Loopback addresses will not work.</p>
            </div>
          </div>
        </div>

        <div className="nms-card space-y-6">
          {/* Site identity */}
          <div>
            <h4 className="text-sm font-semibold font-display text-nms-accent mb-3">Site Identity</h4>
            <div>
              <label className="nms-label">Site Label (for filename only)</label>
              <input
                className="nms-input text-sm"
                value={remoteForm.label}
                onChange={e => setRemote({ label: e.target.value })}
                placeholder="edge-site-1"
              />
            </div>
          </div>

          {/* Network addresses */}
          <div>
            <h4 className="text-sm font-semibold font-display text-nms-accent mb-1">Network Addresses</h4>
            <p className="text-xs text-nms-text-dim mb-3">
              Both must be real routable IPs on the remote site. Loopback will not work.
            </p>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="nms-label">PFCP Address (Gxc)</label>
                <input
                  className="nms-input font-mono text-sm"
                  value={remoteForm.pfcpAddress}
                  onChange={e => setRemote({ pfcpAddress: e.target.value })}
                  placeholder="10.0.1.158"
                />
                <p className="text-xs text-nms-text-dim mt-1">
                  Must be routable from the central SGW-C host.
                </p>
                {remoteForm.pfcpAddress && isLoopback(remoteForm.pfcpAddress) && (
                  <p className="text-xs text-amber-400 mt-1 flex items-center gap-1">
                    <AlertTriangle className="w-3 h-3" /> Cannot be loopback — SGW-C is on a different host
                  </p>
                )}
              </div>
              <div>
                <label className="nms-label">GTP-U Address (S1-U)</label>
                <input
                  className="nms-input font-mono text-sm"
                  value={remoteForm.gtpuAddress}
                  onChange={e => setRemote({ gtpuAddress: e.target.value })}
                  placeholder="10.0.1.158"
                />
                <p className="text-xs text-nms-text-dim mt-1">
                  eNodeBs at this site point S1-U here. Must be reachable from the eNodeBs.
                </p>
                {remoteForm.gtpuAddress && isLoopback(remoteForm.gtpuAddress) && (
                  <p className="text-xs text-amber-400 mt-1 flex items-center gap-1">
                    <AlertTriangle className="w-3 h-3" /> Cannot be loopback — eNodeBs are on different hosts
                  </p>
                )}
              </div>
            </div>
          </div>

          {/* Routing criteria */}
          <div>
            <h4 className="text-sm font-semibold font-display text-nms-accent mb-1">Routing Criteria <span className="text-nms-text-dim font-normal">(optional)</span></h4>
            <p className="text-xs text-nms-text-dim mb-3">
              SGW-C uses this to decide which SGW-U handles each session. Set one criterion only.
              Leave all blank to send all traffic to this SGW-U.
            </p>
            <div className="space-y-3">
              <div>
                <label className="nms-label">TAC <span className="text-nms-text-dim font-normal">(decimal, e.g. 1 or 3,5,8)</span></label>
                <input
                  className="nms-input font-mono text-sm"
                  value={remoteForm.tac}
                  onChange={e => setRemote({ tac: e.target.value, apn: '', eCellId: '' })}
                  placeholder="1  or  3, 5, 8"
                />
                <p className="text-xs text-nms-text-dim mt-1">Route eNodeBs with these Tracking Area Codes here.</p>
              </div>
              <div>
                <label className="nms-label">APN <span className="text-nms-text-dim font-normal">(e.g. internet or ims,internet)</span></label>
                <input
                  className="nms-input font-mono text-sm"
                  value={remoteForm.apn}
                  onChange={e => setRemote({ apn: e.target.value, tac: '', eCellId: '' })}
                  placeholder="internet  or  ims, internet"
                />
                <p className="text-xs text-nms-text-dim mt-1">Route UEs on these APNs here.</p>
              </div>
              <div>
                <label className="nms-label">Cell ID / e_cell_id <span className="text-nms-text-dim font-normal">(hex, 28-bit, e.g. 463 or 123456789,9413)</span></label>
                <input
                  className="nms-input font-mono text-sm"
                  value={remoteForm.eCellId}
                  onChange={e => setRemote({ eCellId: e.target.value, tac: '', apn: '' })}
                  placeholder="463  or  123456789, 9413"
                />
                <p className="text-xs text-nms-text-dim mt-1">Route eNodeBs with these Cell IDs here. Hex representation.</p>
              </div>
            </div>
          </div>

          {/* Log path */}
          <div>
            <h4 className="text-sm font-semibold font-display text-nms-accent mb-3">Logging</h4>
            <div>
              <label className="nms-label">Log File Path</label>
              <input
                className="nms-input font-mono text-sm"
                value={remoteForm.logPath}
                onChange={e => setRemote({ logPath: e.target.value })}
                placeholder="/var/log/open5gs/sgwu.log"
              />
            </div>
          </div>

          {/* Generated YAML */}
          <div>
            <div className="flex items-center justify-between mb-2">
              <h4 className="text-sm font-semibold font-display text-nms-accent">Generated sgwu.yaml</h4>
              <div className="flex gap-2">
                <button
                  onClick={handleAddToSgwcAndApply}
                  disabled={!remoteForm.pfcpAddress || applying}
                  className="nms-btn-ghost text-xs flex items-center gap-1.5"
                  title="Add to SGW-C config and apply"
                >
                  {applying ? (
                    <><span className="w-3.5 h-3.5 border-2 border-current border-t-transparent rounded-full animate-spin inline-block" /> Applying...</>
                  ) : applied ? (
                    <><Check className="w-3.5 h-3.5 text-green-400" /> Applied to SGW-C ✓</>
                  ) : (
                    <><Plus className="w-3.5 h-3.5" /> {remoteAlreadyInSgwc ? 'Update SGW-C & Apply' : 'Add to SGW-C & Apply'}</>
                  )}
                </button>
                <button
                  onClick={handleCopy}
                  className="nms-btn-ghost text-xs flex items-center gap-1.5"
                >
                  {copied ? <Check className="w-3.5 h-3.5 text-green-400" /> : <Copy className="w-3.5 h-3.5" />}
                  {copied ? 'Copied!' : 'Copy'}
                </button>
                <button
                  onClick={handleDownload}
                  className="nms-btn-primary text-xs flex items-center gap-1.5"
                >
                  <Download className="w-3.5 h-3.5" />
                  Download
                </button>
              </div>
            </div>

            <pre className="text-xs font-mono text-nms-text-dim bg-nms-surface-2 border border-nms-border rounded-lg p-4 overflow-x-auto whitespace-pre leading-relaxed">
              {generatedYaml}
            </pre>

            <div className="mt-3 space-y-2">
              <div className="px-3 py-2 bg-amber-500/10 border border-amber-500/30 rounded text-xs text-amber-300 flex items-start gap-2">
                <AlertTriangle className="w-3.5 h-3.5 shrink-0 mt-0.5" />
                <span>
                  <strong>Action required on remote SGW-U host before UEs will work.</strong> See deployment steps below.
                </span>
              </div>

              <div className="px-3 py-2 bg-nms-surface-2/50 rounded border border-nms-border text-xs text-nms-text-dim space-y-2">
                <p className="font-semibold text-nms-text">Deployment steps on the remote host:</p>

                <p className="font-semibold text-nms-text-dim">1. Install Open5GS SGW-U</p>
                <pre className="bg-nms-surface rounded p-2 text-nms-text font-mono overflow-x-auto">{`apt install open5gs-sgwu
cp sgwu-${remoteForm.label || 'remote'}.yaml /etc/open5gs/sgwu.yaml`}</pre>

                <p className="font-semibold text-nms-text-dim">2. Enable IP forwarding</p>
                <pre className="bg-nms-surface rounded p-2 text-nms-text font-mono overflow-x-auto">{`sudo sysctl -w net.ipv4.ip_forward=1
echo "net.ipv4.ip_forward=1" | sudo tee -a /etc/sysctl.conf`}</pre>

                <p className="font-semibold text-nms-text-dim">3. Ensure firewall allows PFCP and GTP-U</p>
                <pre className="bg-nms-surface rounded p-2 text-nms-text font-mono overflow-x-auto">{`sudo ufw allow 8805/udp   # PFCP
sudo ufw allow 2152/udp   # GTP-U`}</pre>

                <p className="font-semibold text-nms-text-dim">4. Start the SGW-U service</p>
                <pre className="bg-nms-surface rounded p-2 text-nms-text font-mono overflow-x-auto">{`sudo systemctl enable --now open5gs-sgwud
sudo systemctl status open5gs-sgwud`}</pre>

                <div className="px-3 py-2 bg-blue-500/10 border border-blue-500/20 rounded text-xs text-blue-300 space-y-1">
                  <p className="font-semibold">Important: internet breakout is handled by the UPF, not SGW-U</p>
                  <p>The SGW-U only terminates the S1-U GTP tunnel from the eNodeB and forwards packets to the central PGW/UPF. For local internet breakout at the edge site you also need to deploy a remote UPF on this host — use the UPF Config page to generate the upf.yaml and add it to the SMF.</p>
                </div>

                <p className="font-semibold text-nms-text pt-1">
                  Central SGW-C is auto-configured when you click "Add to SGW-C &amp; Apply" above.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>
  );
}
