import { useState, useEffect } from 'react';
import { Plus, Server, AlertTriangle, Info, Download, Copy, Check, Radio } from 'lucide-react';
import type { AllConfigs } from '../../../types';
import { LoggerSection } from './SharedComponents';
import { LabelWithTooltip } from '../../common/UniversalTooltipWrappers';
import { COMMON_TOOLTIPS, UPF_TOOLTIPS } from '../../../data/tooltips';

interface Props {
  configs: AllConfigs;
  onChange: (c: AllConfigs) => void;
  onApply?: (configs: AllConfigs) => Promise<void>;
  editUpfData?: any;
  onEditUpfDataConsumed?: () => void;
}

interface RemoteUpfForm {
  label: string;
  pfcpAddress: string;
  gtpuAddress: string;
  subnet: string;
  gateway: string;
  dnn: string;
  logPath: string;
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function isLoopback(ip: string): boolean {
  return ip.startsWith('127.') || ip === 'localhost';
}

function FieldRow({
  label,
  value,
  onChange,
  placeholder,
  tooltip,
  mono = true,
  type = 'text',
}: {
  label: string;
  value: string | number;
  onChange: (v: string) => void;
  placeholder?: string;
  tooltip?: string;
  mono?: boolean;
  type?: string;
}) {
  return (
    <div>
      <label className="nms-label">
        {tooltip ? <LabelWithTooltip tooltip={tooltip}>{label}</LabelWithTooltip> : label}
      </label>
      <input
        type={type}
        className={`nms-input text-sm ${mono ? 'font-mono' : ''}`}
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder={placeholder}
      />
    </div>
  );
}

// ── YAML Generator ────────────────────────────────────────────────────────────

function generateRemoteUpfYaml(form: RemoteUpfForm, smfDisplayAddress: string): string {
  const lines: string[] = [];

  lines.push(`logger:`);
  lines.push(`  file:`);
  lines.push(`    path: ${form.logPath || '/var/log/open5gs/upf.log'}`);
  lines.push(``);
  lines.push(`# Remote UPF: ${form.label || 'Edge Site'}`);
  lines.push(`# Generated by open5gs-nms`);
  lines.push(`# Deploy this file to: /etc/open5gs/upf.yaml on the remote UPF host`);
  lines.push(`# The SMF at ${smfDisplayAddress} must be able to reach ${form.pfcpAddress || '<PFCP-IP>'} on UDP/8805`);
  lines.push(``);
  lines.push(`upf:`);
  lines.push(`  pfcp:`);
  lines.push(`    server:`);
  lines.push(`      - address: ${form.pfcpAddress || '172.16.10.20'}`);
  if (smfDisplayAddress && smfDisplayAddress !== '<SMF-real-routable-IP>') {
    lines.push(`    client:`);
    lines.push(`      smf:`);
    lines.push(`        - address: ${smfDisplayAddress}`);
  }
  lines.push(``);
  lines.push(`  gtpu:`);
  lines.push(`    server:`);
  lines.push(`      - address: ${form.gtpuAddress || '172.16.10.21'}`);
  lines.push(``);
  lines.push(`  session:`);
  lines.push(`    - subnet: ${form.subnet || '10.45.0.0/16'}`);
  lines.push(`      gateway: ${form.gateway || '10.45.0.1'}`);
  if (form.dnn) {
    lines.push(`      dnn: ${form.dnn}`);
  }
  lines.push(``);

  return lines.join('\n');
}

// ── Main component ────────────────────────────────────────────────────────────

export function UpfEditor({ configs, onChange, onApply, editUpfData, onEditUpfDataConsumed }: Props): JSX.Element {
  // ── Local UPF (upf.yaml) ──
  const upfFullYaml = configs.upf as any;
  const upf = upfFullYaml?.upf || {};
  const pfcpServer = upf.pfcp?.server?.[0] || { address: '127.0.0.7' };
  const gtpuServer = upf.gtpu?.server?.[0] || { address: '10.0.1.155' };

  // ── SMF (smf.yaml) — PFCP UPF client list ──
  const smfFullYaml = configs.smf as any;
  const smf = smfFullYaml?.smf || {};
  const upfClients: Array<{ address: string }> = smf.pfcp?.client?.upf || [{ address: '127.0.0.7' }];

  const smfSbiAddress: string = smf.sbi?.server?.[0]?.address || '';
  const smfPfcpServer0: string = smf.pfcp?.server?.[0]?.address || '';
  const smfPfcpServer1: string = smf.pfcp?.server?.[1]?.address || '';

  // Find the first real routable (non-loopback) SMF address to show in the
  // remote UPF generator. Priority: PFCP server[1] (the one the user just
  // added for remote UPF), then SBI server, then PFCP server[0].
  // Falls back to placeholder if none is a real routable IP.
  const smfRealAddress: string =
    (!isLoopback(smfPfcpServer1) && smfPfcpServer1 ? smfPfcpServer1 : '') ||
    (!isLoopback(smfSbiAddress)  && smfSbiAddress  ? smfSbiAddress  : '') ||
    (!isLoopback(smfPfcpServer0) && smfPfcpServer0 ? smfPfcpServer0 : '') ||
    '';
  const smfPfcpDisplayAddress = smfRealAddress || '<SMF-real-routable-IP>';

  // ── Remote UPF generator state ──
  const [remoteForm, setRemoteForm] = useState<RemoteUpfForm>({
    label: '',
    pfcpAddress: '',
    gtpuAddress: '',
    subnet: upf.session?.[0]?.subnet || '10.45.0.0/16',
    gateway: upf.session?.[0]?.gateway || '10.45.0.1',
    dnn: upf.session?.[0]?.dnn || 'internet',
    logPath: '/var/log/open5gs/upf.log',
  });
  const [copied, setCopied] = useState(false);

  const [applying, setApplying] = useState(false);
  const [applied, setApplied] = useState(false);

  // Pre-populate form when navigated here from SmfEditor
  useEffect(() => {
    if (!editUpfData) return;
    setRemoteForm(prev => ({
      ...prev,
      pfcpAddress: editUpfData.pfcpAddress || prev.pfcpAddress,
      dnn:         editUpfData.dnn         || prev.dnn,
      subnet:      editUpfData.subnet      || prev.subnet,
      gateway:     editUpfData.gateway     || prev.gateway,
    }));
    onEditUpfDataConsumed?.();
    // Scroll generator into view
    setTimeout(() => {
      document.getElementById('remote-upf-generator')?.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }, 100);
  }, [editUpfData]);

  const setRemote = (patch: Partial<RemoteUpfForm>) =>
    setRemoteForm(prev => ({ ...prev, ...patch }));

  const generatedYaml = generateRemoteUpfYaml(remoteForm, smfPfcpDisplayAddress);

  const handleCopy = () => {
    navigator.clipboard.writeText(generatedYaml).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const handleDownload = () => {
    const blob = new Blob([generatedYaml], { type: 'text/yaml' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    const siteName = remoteForm.label
      ? remoteForm.label.toLowerCase().replace(/[^a-z0-9]/g, '-')
      : 'remote-upf';
    a.href = url;
    a.download = `upf-${siteName}.yaml`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleAddToSmf = async () => {
    if (!remoteForm.pfcpAddress) return;

    // Build the new UPF client entry with DNN routing rule if specified
    const newUpfClient: any = { address: remoteForm.pfcpAddress };
    if (remoteForm.dnn) newUpfClient.dnn = remoteForm.dnn;

    // Add UPF to SMF pfcp.client.upf (skip if already there)
    const alreadyInUpf = upfClients.some(c => c.address === remoteForm.pfcpAddress);
    const newUpfClients = alreadyInUpf
      ? upfClients.map(c => c.address === remoteForm.pfcpAddress ? newUpfClient : c)
      : [...upfClients, newUpfClient];

    // Build matching session for this DNN if one doesn't exist
    const existingSessions: any[] = smf.session || [];
    const sessionExists = remoteForm.dnn
      ? existingSessions.some((s: any) => s.dnn === remoteForm.dnn)
      : false;

    // Helper: sort so DNN-specific sessions come before default (no-DNN) ones
    const sortSessions = (sess: any[]) => [
      ...sess.filter((s: any) => s.dnn),
      ...sess.filter((s: any) => !s.dnn),
    ];

    const newSessions = sessionExists || !remoteForm.dnn
      ? existingSessions
      : sortSessions([...existingSessions, {
          subnet: remoteForm.subnet,
          gateway: remoteForm.gateway,
          dnn: remoteForm.dnn,
        }]);

    // Build updated configs with both UPF client and session changes
    const updatedConfigs: AllConfigs = {
      ...configs,
      smf: {
        ...smfFullYaml,
        smf: {
          ...smf,
          pfcp: {
            ...smf.pfcp,
            client: { ...smf.pfcp?.client, upf: newUpfClients },
          },
          session: newSessions,
        },
      },
    };

    // Update state then auto-apply
    onChange(updatedConfigs);
    if (onApply) {
      await onApply(updatedConfigs);
    }
  };

  // ── Updaters ──────────────────────────────────────────────────────────────

  const updateUpf = (partial: any) => {
    onChange({ ...configs, upf: { ...upfFullYaml, upf: { ...upf, ...partial } } });
  };

  const updateUpfLogger = (logger: any) => {
    onChange({ ...configs, upf: { ...upfFullYaml, logger } });
  };

  if (!upf?.pfcp?.server || upf.pfcp.server.length === 0) {
    return <div className="text-nms-text-dim py-4">Loading UPF configuration...</div>;
  }

  const handleAddToSmfAndApply = async () => {
    setApplying(true);
    try {
      await handleAddToSmf();
      setApplied(true);
      setTimeout(() => setApplied(false), 3000);
    } finally {
      setApplying(false);
    }
  };

  const remoteAlreadyInSmf = remoteForm.pfcpAddress
    ? upfClients.some(c => c.address === remoteForm.pfcpAddress)
    : false;

  return (
    <div className="space-y-8">

      {/* ── Section 1: Local UPF ── */}
      <div>
        <div className="flex items-center gap-3 mb-4">
          <div className="p-2 rounded-lg bg-nms-accent/10 text-nms-accent">
            <Server className="w-4 h-4" />
          </div>
          <div>
            <h3 className="text-base font-semibold font-display text-nms-text">
              Local UPF — <span className="font-mono text-nms-accent">/etc/open5gs/upf.yaml</span>
            </h3>
            <p className="text-xs text-nms-text-dim">
              The UPF running on this Open5GS host. PFCP can use loopback; GTP-U must use a real routable IP
              that radios can reach.
            </p>
          </div>
        </div>

        <div className="nms-card space-y-6">
          <div>
            <h4 className="text-sm font-semibold font-display text-nms-accent mb-3">
              PFCP Server (N4 — SMF control plane)
            </h4>
            <div className="grid grid-cols-2 gap-4">
              <FieldRow
                label="Address"
                value={pfcpServer.address}
                onChange={(v) => updateUpf({ pfcp: { ...upf.pfcp, server: [{ ...pfcpServer, address: v }] } })}
                placeholder="127.0.0.7"
                tooltip="PFCP server address. Can be loopback (127.0.0.7) when SMF and UPF are on the same host."
              />
              <FieldRow
                label="Port"
                value={pfcpServer.port ?? ''}
                onChange={(v) => {
                  const updated = { ...pfcpServer };
                  if (v !== '') (updated as any).port = parseInt(v) || 8805;
                  else delete (updated as any).port;
                  updateUpf({ pfcp: { ...upf.pfcp, server: [updated] } });
                }}
                placeholder="8805 (default)"
                type="number"
                tooltip="PFCP port (default 8805). Usually omitted to use the default."
              />
            </div>
          </div>

          <div>
            <h4 className="text-sm font-semibold font-display text-nms-accent mb-1">
              GTP-U Server (N3 / S1-U — radio user plane)
            </h4>
            <p className="text-xs text-nms-text-dim mb-3">
              Must be a real routable IP — radios send UE user traffic directly here over UDP/2152. Cannot be loopback.
            </p>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <FieldRow
                  label="Address"
                  value={gtpuServer.address}
                  onChange={(v) => updateUpf({ gtpu: { server: [{ ...gtpuServer, address: v }] } })}
                  placeholder="10.0.1.155"
                  tooltip={UPF_TOOLTIPS.gtpu_address}
                />
                {isLoopback(gtpuServer.address) && (
                  <div className="mt-1.5 flex items-start gap-1.5 text-xs text-amber-400">
                    <AlertTriangle className="w-3.5 h-3.5 shrink-0 mt-0.5" />
                    <span>GTP-U address is loopback — remote radios will not be able to send user traffic here.</span>
                  </div>
                )}
              </div>
              <FieldRow
                label="Port"
                value={gtpuServer.port ?? ''}
                onChange={(v) => {
                  const updated = { ...gtpuServer };
                  if (v !== '') (updated as any).port = parseInt(v) || 2152;
                  else delete (updated as any).port;
                  updateUpf({ gtpu: { server: [updated] } });
                }}
                placeholder="2152 (default)"
                type="number"
                tooltip={UPF_TOOLTIPS.gtpu_port}
              />
            </div>
          </div>

          {upf.session && upf.session.length > 0 && (
            <div>
              <h4 className="text-sm font-semibold font-display text-nms-accent mb-3">Session Pools</h4>
              {upf.session.map((sess: any, i: number) => (
                <div key={i} className="grid grid-cols-2 gap-4 mb-2">
                  <FieldRow
                    label="Subnet"
                    value={sess.subnet || ''}
                    onChange={(v) => {
                      const updated = [...upf.session];
                      updated[i] = { ...updated[i], subnet: v };
                      updateUpf({ session: updated });
                    }}
                    placeholder="10.45.0.0/16"
                    tooltip={UPF_TOOLTIPS.session_subnet}
                  />
                  <FieldRow
                    label="Gateway"
                    value={sess.gateway || ''}
                    onChange={(v) => {
                      const updated = [...upf.session];
                      updated[i] = { ...updated[i], gateway: v };
                      updateUpf({ session: updated });
                    }}
                    placeholder="10.45.0.1"
                    tooltip={UPF_TOOLTIPS.session_gateway}
                  />
                </div>
              ))}
            </div>
          )}

          <div>
            <h4 className="text-sm font-semibold font-display text-nms-accent mb-3">Metrics Server</h4>
            <div className="grid grid-cols-2 gap-4">
              <FieldRow
                label="Address"
                value={upf.metrics?.server?.[0]?.address || ''}
                onChange={(v) => updateUpf({ metrics: { server: [{ address: v, port: upf.metrics?.server?.[0]?.port || 9090 }] } })}
                tooltip={COMMON_TOOLTIPS.metrics_address}
              />
              <FieldRow
                label="Port"
                type="number"
                value={upf.metrics?.server?.[0]?.port || 9090}
                onChange={(v) => updateUpf({ metrics: { server: [{ address: upf.metrics?.server?.[0]?.address || '', port: parseInt(v) || 9090 }] } })}
                tooltip={COMMON_TOOLTIPS.metrics_port}
              />
            </div>
          </div>

          <LoggerSection logger={upfFullYaml.logger || {}} onChange={updateUpfLogger} />
        </div>
      </div>

      {/* ── Section 2: Remote UPF YAML Generator ── */}
      <div id="remote-upf-generator">
        <div className="flex items-center gap-3 mb-4">
          <div className="p-2 rounded-lg bg-purple-500/10 text-purple-400">
            <Radio className="w-4 h-4" />
          </div>
          <div>
            <h3 className="text-base font-semibold font-display text-nms-text">
              Remote UPF Config Generator
            </h3>
            <p className="text-xs text-nms-text-dim">
              Fill in the details for your remote edge UPF. This generates a ready-to-deploy{' '}
              <span className="font-mono">upf.yaml</span> to copy to the remote machine.
              The remote UPF only needs <span className="font-mono">open5gs-upfd</span> installed.
            </p>
          </div>
        </div>

        {/* How it works explainer */}
        <div className="nms-card bg-purple-500/5 border-purple-500/20 mb-4">
          <div className="flex items-start gap-3">
            <Info className="w-4 h-4 text-purple-400 mt-0.5 shrink-0" />
            <div className="text-xs text-nms-text-dim space-y-1">
              <p className="font-semibold text-nms-text">How distributed UPF works:</p>
              <p>
                <span className="text-purple-300">SMF → Remote UPF</span> over <span className="font-mono">PFCP/N4 (UDP/8805)</span> — the SMF
                sends session rules to the remote UPF. The central Open5GS SMF is at{' '}
                <span className="font-mono text-nms-accent">{smfPfcpDisplayAddress}</span>.
              </p>
              <p>
                <span className="text-purple-300">Radio → Remote UPF</span> over <span className="font-mono">GTP-U/N3 (UDP/2152)</span> — UE user
                traffic goes directly from the radio to the remote UPF, never touching the central site WAN.
              </p>
              <p>Both the PFCP and GTP-U addresses must be routable between sites. Loopback addresses will not work.</p>
            </div>
          </div>
        </div>

        <div className="nms-card space-y-6">
          {/* Identity */}
          <div>
            <h4 className="text-sm font-semibold font-display text-nms-accent mb-3">Site Identity</h4>
            <FieldRow
              label="Site Label (for filename only)"
              value={remoteForm.label}
              onChange={(v) => setRemote({ label: v })}
              placeholder="edge-site-1"
              mono={false}
              tooltip="Used only to name the downloaded file. Not written to the YAML."
            />
          </div>

          {/* Network addresses */}
          <div>
            <h4 className="text-sm font-semibold font-display text-nms-accent mb-1">Network Addresses</h4>
            <p className="text-xs text-nms-text-dim mb-3">
              Both must be real routable IPs on the remote site. Loopback will not work.
            </p>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <FieldRow
                  label="PFCP Address (N4)"
                  value={remoteForm.pfcpAddress}
                  onChange={(v) => setRemote({ pfcpAddress: v })}
                  placeholder="172.16.10.20"
                  tooltip="The IP the SMF will use to reach this UPF over PFCP/N4. Must be routable from the central Open5GS host."
                />
                {remoteForm.pfcpAddress && isLoopback(remoteForm.pfcpAddress) && (
                  <p className="text-xs text-amber-400 mt-1 flex items-center gap-1">
                    <AlertTriangle className="w-3 h-3" /> Cannot be loopback — SMF is on a different host
                  </p>
                )}
              </div>
              <div>
                <FieldRow
                  label="GTP-U Address (N3 / S1-U)"
                  value={remoteForm.gtpuAddress}
                  onChange={(v) => setRemote({ gtpuAddress: v })}
                  placeholder="172.16.10.21"
                  tooltip="The IP radios will use to send UE user traffic. Must be reachable from the radio at the edge site."
                />
                {remoteForm.gtpuAddress && isLoopback(remoteForm.gtpuAddress) && (
                  <p className="text-xs text-amber-400 mt-1 flex items-center gap-1">
                    <AlertTriangle className="w-3 h-3" /> Cannot be loopback — radios are on a different host
                  </p>
                )}
              </div>
            </div>
          </div>

          {/* Session */}
          <div>
            <h4 className="text-sm font-semibold font-display text-nms-accent mb-3">Session Pool</h4>
            <div className="grid grid-cols-3 gap-4">
              <FieldRow
                label="Subnet"
                value={remoteForm.subnet}
                onChange={(v) => setRemote({ subnet: v })}
                placeholder="10.45.0.0/16"
                tooltip="UE IP address pool for this UPF. Should match your central UPF subnet unless you are splitting pools."
              />
              <FieldRow
                label="Gateway"
                value={remoteForm.gateway}
                onChange={(v) => setRemote({ gateway: v })}
                placeholder="10.45.0.1"
                tooltip="TUN interface gateway address created by the UPF on the remote host."
              />
              <FieldRow
                label="DNN (optional)"
                value={remoteForm.dnn}
                onChange={(v) => setRemote({ dnn: v })}
                placeholder="internet"
                tooltip="Data Network Name. Leave blank to handle all DNNs, or specify to route only a specific DNN to this UPF."
              />
            </div>
          </div>

          {/* Log path */}
          <div>
            <h4 className="text-sm font-semibold font-display text-nms-accent mb-3">Logging</h4>
            <FieldRow label="Log File Path" value={remoteForm.logPath} onChange={(v) => setRemote({ logPath: v })} placeholder="/var/log/open5gs/upf.log" tooltip="Log file path on the remote UPF host." />
          </div>

          {/* Generated YAML */}
          <div>
            <div className="flex items-center justify-between mb-2">
              <h4 className="text-sm font-semibold font-display text-nms-accent">
                Generated upf.yaml
              </h4>
              <div className="flex gap-2">
                {/* Add to SMF + Auto-apply button */}
                <button
                  onClick={handleAddToSmfAndApply}
                  disabled={!remoteForm.pfcpAddress || applying}
                  className="nms-btn-ghost text-xs flex items-center gap-1.5"
                  title="Add to SMF config and apply immediately"
                >
                  {applying ? (
                    <><span className="w-3.5 h-3.5 border-2 border-current border-t-transparent rounded-full animate-spin inline-block" /> Applying...</>
                  ) : applied ? (
                    <><Check className="w-3.5 h-3.5 text-nms-green" /> Applied to SMF ✓</>
                  ) : (
                    <><Plus className="w-3.5 h-3.5" /> {remoteAlreadyInSmf ? 'Update SMF & Apply' : 'Add to SMF & Apply'}</>
                  )}
                </button>
                <button
                  onClick={handleCopy}
                  className="nms-btn-ghost text-xs flex items-center gap-1.5"
                  title="Copy to clipboard"
                >
                  {copied ? <Check className="w-3.5 h-3.5 text-nms-green" /> : <Copy className="w-3.5 h-3.5" />}
                  {copied ? 'Copied!' : 'Copy'}
                </button>
                <button
                  onClick={handleDownload}
                  className="nms-btn-primary text-xs flex items-center gap-1.5"
                  title="Download as upf.yaml"
                >
                  <Download className="w-3.5 h-3.5" />
                  Download
                </button>
              </div>
            </div>

            <pre className="text-xs font-mono text-nms-text-dim bg-nms-surface-2 border border-nms-border rounded-lg p-4 overflow-x-auto whitespace-pre leading-relaxed">
              {generatedYaml}
            </pre>

            <div className="mt-3 space-y-2">
              {/* NAT Warning */}
              <div className="px-3 py-2 bg-amber-500/10 border border-amber-500/30 rounded text-xs text-amber-300 flex items-start gap-2">
                <AlertTriangle className="w-3.5 h-3.5 shrink-0 mt-0.5" />
                <span>
                  <strong>Action required on remote UPF host before UEs will work.</strong> See deployment steps below.
                </span>
              </div>
              {/* Deployment steps */}
              <div className="px-3 py-2 bg-nms-surface-2/50 rounded border border-nms-border text-xs text-nms-text-dim space-y-2">
                <p className="font-semibold text-nms-text">Deployment steps on the remote host:</p>

                <p className="font-semibold text-nms-text-dim">1. Install &amp; configure Open5GS UPF</p>
                <pre className="bg-nms-surface rounded p-2 text-nms-text font-mono overflow-x-auto">{`apt install open5gs-upf
cp upf.yaml /etc/open5gs/upf.yaml`}</pre>

                <p className="font-semibold text-nms-text-dim">2. Assign gateway IP to TUN interface</p>
                <p className="text-nms-text-dim">Open5GS creates the ogstun interface but does NOT assign the IP — you must do this manually:</p>
                <pre className="bg-nms-surface rounded p-2 text-nms-text font-mono overflow-x-auto">{`sudo ip addr add ${remoteForm.gateway || '10.x.x.1'}/${(remoteForm.subnet || '').split('/')[1] || '16'} dev ogstun
sudo ip link set ogstun up`}</pre>
                <p className="text-amber-300">⚠️ Add to a startup script to persist across reboots.</p>

                <p className="font-semibold text-nms-text-dim">3. Enable IP forwarding &amp; configure NAT</p>
                <p className="text-nms-text-dim">Replace <span className="font-mono text-nms-accent">eth0</span> with your internet-facing interface (<span className="font-mono">ip route | grep default</span>):</p>
                <pre className="bg-nms-surface rounded p-2 text-nms-text font-mono overflow-x-auto">{`# Enable IP forwarding
sudo sysctl -w net.ipv4.ip_forward=1
echo "net.ipv4.ip_forward=1" | sudo tee -a /etc/sysctl.conf

# NAT masquerading (replace eth0 with your interface)
sudo iptables -t nat -A POSTROUTING -s ${remoteForm.subnet || '10.x.x.x/16'} ! -o ogstun -j MASQUERADE
sudo iptables -I INPUT -i ogstun -j ACCEPT

# Make persistent
sudo apt-get install -y iptables-persistent
sudo netfilter-persistent save`}</pre>

                <p className="font-semibold text-nms-text-dim">4. Ensure firewall allows PFCP</p>
                <pre className="bg-nms-surface rounded p-2 text-nms-text font-mono overflow-x-auto">{`sudo ufw allow 8805/udp`}</pre>

                <p className="font-semibold text-nms-text-dim">5. Start the UPF service</p>
                <pre className="bg-nms-surface rounded p-2 text-nms-text font-mono overflow-x-auto">{`sudo systemctl enable --now open5gs-upfd
sudo systemctl status open5gs-upfd`}</pre>

                <p className="font-semibold text-nms-text pt-1">Central SMF is auto-configured when you click "Add to SMF &amp; Apply" above.</p>
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>
  );
}
